-- TECH-144 preflight-hardening deliverable: reference only, NEVER executed
-- by this story (no terraform apply, no real RDS instance exists yet, no
-- AWS connection of any kind is made by this file or anything that reads
-- it). Documents the exact grants for the two-user strategy chosen to
-- replace the RDS master secret currently wired (temporarily) into the ECS
-- task definition (see modules/ecs-task/README.md and
-- modules/database/README.md).
--
-- Run once, manually, by whoever holds the master credential, against the
-- real RDS instance, after it exists — before the application's task
-- definition is repointed at either of these two users' Secrets Manager
-- entries. Table names below match the real Flyway schema
-- (src/main/resources/db/migration/V1__initial_schema.sql and later). This
-- script never runs Flyway itself — it only prepares the two roles Flyway
-- and the application will use.
--
-- Two users, not one:
--   sipsa_migration — owns the schema, runs Flyway (DDL: CREATE/ALTER/DROP
--                     TABLE, index management). Used only at deploy time
--                     (the one-off migration task — see the Flyway
--                     decision in docs/operations/aws-production-preflight.md),
--                     never by the running application.
--   sipsa_runtime   — DML only (SELECT/INSERT/UPDATE/DELETE) on the
--                     application's own tables. No DDL, no ownership. Used
--                     by the ECS service's own task definition, always.
-- Rationale: if the running application is ever compromised (e.g. a
-- dependency vulnerability), the runtime credential alone cannot alter the
-- schema, create new tables, or drop anything — a real, load-bearing
-- security boundary, not a formality.
--
-- Neither role is granted SUPERUSER, CREATEROLE, CREATEDB, or REPLICATION —
-- confirmed by inspection: no such clause appears anywhere below. Only the
-- specific schema/table/sequence grants each role actually needs.
--
-- NOT idempotent, deliberately: PostgreSQL's CREATE ROLE has no
-- "IF NOT EXISTS" clause. Re-running this script against a database where
-- these roles already exist will fail on the CREATE ROLE statements with
-- "role already exists" — intentional, not an oversight. Silently
-- swallowing that error (e.g. via a DO block with an EXCEPTION handler)
-- would risk masking a real mistake (running this against the wrong
-- database) or silently no-op'ing a password rotation the operator
-- actually intended. If a role already exists and only the GRANT
-- statements need re-applying (e.g. after adding a new table outside of
-- Flyway, which should not normally happen), run only the GRANT/ALTER
-- DEFAULT PRIVILEGES statements below, not the CREATE ROLE lines — those
-- are safe to re-run (GRANT is idempotent in PostgreSQL: re-granting a
-- privilege a role already has is a silent no-op, not an error).

-- Replace the two placeholder passwords below with values generated by
-- Secrets Manager (aws_secretsmanager_secret + random_password, mirroring
-- the pattern already used for the M2M Cognito client secret) — never a
-- literal password committed to this file or anywhere else in the
-- repository.

CREATE ROLE sipsa_migration WITH LOGIN PASSWORD '__REPLACE_VIA_SECRETS_MANAGER__';
CREATE ROLE sipsa_runtime WITH LOGIN PASSWORD '__REPLACE_VIA_SECRETS_MANAGER__';

-- --- sipsa_migration: schema ownership, DDL, Flyway's own history table ---

GRANT CREATE, USAGE ON SCHEMA public TO sipsa_migration;
ALTER SCHEMA public OWNER TO sipsa_migration;

-- Flyway needs full DML+DDL on its own history table plus every
-- application table it creates/migrates.
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sipsa_migration;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sipsa_migration;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO sipsa_migration;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO sipsa_migration;

-- --- sipsa_runtime: DML only, on the tables the application actually uses ---

GRANT USAGE ON SCHEMA public TO sipsa_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  ingestion_runs,
  ingestion_audit,
  ingestion_rejects,
  sipsa_ciudad,
  sipsa_parcial,
  sipsa_mayoristas_semanal,
  sipsa_mayoristas_mensual,
  sipsa_abastecimientos_mensual
TO sipsa_runtime;

-- Sequences backing the SERIAL/IDENTITY primary keys above — INSERT needs
-- nextval() on each.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sipsa_runtime;

-- Future tables Flyway creates automatically grant DML to sipsa_runtime —
-- without this, every new migration would silently need a manual grant
-- statement added here, an easy step to forget. This ALTER DEFAULT
-- PRIVILEGES statement (like the GRANTs above) is safe to re-run.
ALTER DEFAULT PRIVILEGES FOR ROLE sipsa_migration IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sipsa_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE sipsa_migration IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO sipsa_runtime;

-- sipsa_runtime explicitly does NOT get: CREATE on the schema, ownership of
-- any table, DROP/ALTER/TRUNCATE on anything, or any Flyway history table
-- access. Confirmed intentional, not an oversight.
