-- -------------------------------------------------------------------------------------------------
-- V3 — Drop the redundant explicit key_hash index on sipsa_parcial (TECH-119)
--
-- V1 created BOTH an explicit non-unique index and a UNIQUE constraint on the same
-- column, leaving key_hash indexed twice with identical B-tree definitions:
--
--   idx_sipsa_parcial_key_hash   CREATE INDEX ... USING btree (key_hash)          ← dropped here
--   sipsa_parcial_key_hash_key   CREATE UNIQUE INDEX ... USING btree (key_hash)   ← preserved
--                                (backing index of the UNIQUE (key_hash) constraint)
--
-- With the deterministic hash of TECH-011, key_hash lookups run on every ingestion
-- batch; the duplicate index only doubles write amplification and storage (80 MB each
-- at 676K rows) without adding any capability: the unique index serves every lookup
-- the non-unique one served, and the constraint is untouched by this DROP (it owns its
-- own backing index).
--
-- Execution choice — plain transactional DROP INDEX (not CONCURRENTLY): no environment
-- with live traffic exists yet (AWS deployment is pending, TECH-130..132), the drop is
-- a near-instant metadata operation, and a transactional migration rolls back cleanly
-- on failure. If an environment with concurrent traffic ever needs this migration on a
-- large table, apply it in a brief window — documented in the database changelog.
--
-- Deliberately NO "IF EXISTS": if the index is already gone, the schema has drifted
-- from the migration history and this migration must fail loudly (ADR-009).
-- -------------------------------------------------------------------------------------------------

DROP INDEX idx_sipsa_parcial_key_hash;
